
export const COURSES = [
  {
    id: "react-js",
    title: "React JS",
    category: "Frontend",
    duration: "8 weeks",
    level: "Intermediate",
    highlights: ["JSX & Components", "State & Hooks", "Routing (React Router)", "Projects & Deployments"],
    color: "blue",
    image: "/images/react.jpeg",
  },
  {
    id: "angular",
    title: "Angular",
    category: "Frontend",
    duration: "10 weeks",
    level: "Intermediate",
    highlights: ["TypeScript & Angular CLI", "Components & Services", "RxJS", "NgRx (optional)"] ,
    color: "purple",
    image: "/images/angular.jpeg",
  },
  {
    id: "node-backend",
    title: "Node.js Backend",
    category: "Backend",
    duration: "8 weeks",
    level: "Intermediate",
    highlights: ["Express.js", "REST APIs", "Authentication", "Databases (Mongo/Postgres)"],
    color: "green",
    image: "/images/node.png",
  },
  {
    id: "python",
    title: "Python",
    category: "General",
    duration: "6 weeks",
    level: "Beginner",
    highlights: ["Python Basics", "OOP", "Scripts & Automation", "Intro to Web (Flask)"],
    color: "yellow",
    image: "/images/python.jpeg",
  },
  {
    id: "dotnet",
    title: ".NET (C#)",
    category: "Backend",
    duration: "10 weeks",
    level: "Intermediate",
    highlights: ["C# Fundamentals", "ASP.NET Core", "Entity Framework", "Microservices Basics"],
    color: "red",
    image: "/images/dotnet.png",
  },
  {
    id: "python-backend",
    title: "Python Backend",
    category: "Backend",
    duration: "8 weeks",
    level: "Intermediate",
    highlights: ["Flask/Django", "APIs & Authentication", "ORMs", "Deployments"],
    color: "teal",
    image: "/images/download.jpeg",
  },
];
